#spring.application.name=SECD
#??
server:
  port: 8000
spring:

  datasource:
    url: jdbc:mysql://db.liukanshan.top:3306/ty
    username: ty
    password: SziwKbAh3PNZ2643
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev # ??????????profile??????????????profile??

  # ????????????????????
  servlet:
    multipart:
      max-file-size: 10MB # ?????????????????????????
      max-request-size: 10MB

  jackson:
    serialization:
      indent-output: true # ????????JSON???

mybatis:
  type-aliases-package: com.example.secd  # ?????????
  mapper-locations: classpath:mapper/*.xml  # MyBatis mapper?????

# MyBatis???
mybatis.configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # MyBatis????????????SQL??
  cache-enabled: true  # ??????????true
  # ??MyBatis???...

debug: true



